package bwie.example.com.bwshop.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bwie.example.com.bwshop.model.ChacheBean;

import bwie.example.com.bwshop.greendao.ChacheBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chacheBeanDaoConfig;

    private final ChacheBeanDao chacheBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chacheBeanDaoConfig = daoConfigMap.get(ChacheBeanDao.class).clone();
        chacheBeanDaoConfig.initIdentityScope(type);

        chacheBeanDao = new ChacheBeanDao(chacheBeanDaoConfig, this);

        registerDao(ChacheBean.class, chacheBeanDao);
    }
    
    public void clear() {
        chacheBeanDaoConfig.clearIdentityScope();
    }

    public ChacheBeanDao getChacheBeanDao() {
        return chacheBeanDao;
    }

}
